name: dobify_store
description: "Dobify at Store"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.6.0
  intl: ^0.20.0
  razorpay_flutter: ^1.3.5
  google_maps_flutter_web: ^0.5.7
  geolocator_web: ^4.1.3
  google_maps_flutter: ^2.6.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  google_sign_in: ^6.0.0
  app_links: ^6.1.4
  permission_handler: ^12.0.1
  flutter_typeahead: ^5.0.0
  http: ^1.1.0
  easy_localization: ^3.0.3
  share_plus: ^10.1.2  # ⬅️ UPDATED VERSION
  pdf: ^3.10.4
  path_provider: ^2.1.4  # ⬅️ UPDATED VERSION
  printing: ^5.11.3
  url_launcher: ^6.3.1  # ⬅️ ADD THIS (you're already using it in code)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/blue_pin.png
    - assets/images/dobify_inv_logo.jpg
    - assets/images/payment_qr.png
    # This will include all images in the folder